const path = require('node:path');
const os = require('node:os');
const home = os.homedir();
const join = (...parts) => path.join(home, ...parts);
const platformPaths = ({ darwin = [], win32 = [], linux = [] }) => ({ darwin, win32, linux });
const adapters = [
  { id:'cursor', name:'Cursor', paths:platformPaths({darwin:[join('Library/Application Support/Cursor/User/settings.json')],win32:[join('AppData/Roaming/Cursor/User/settings.json')],linux:[join('.config/Cursor/User/settings.json')]}), format:'json', patch:(c,i)=>({...c, 'openai.apiBase':i.baseURL, 'openai.apiKey':i.apiKey, 'openai.model':i.model}) },
  { id:'claude-code', name:'Claude Code', paths:platformPaths({darwin:[join('.claude/settings.json')],win32:[join('.claude/settings.json')],linux:[join('.claude/settings.json')]}), format:'json', patch:(c,i)=>({...c, env:{...(c.env||{}), ANTHROPIC_BASE_URL:i.baseURL, ANTHROPIC_API_KEY:i.apiKey, ANTHROPIC_MODEL:i.model}}) },
  { id:'codex', name:'Codex CLI', paths:platformPaths({darwin:[join('.codex/config.toml')],win32:[join('.codex/config.toml')],linux:[join('.codex/config.toml')]}), format:'toml', patch:(_,i)=>`model = "${i.model}"\nmodel_provider = "ccapi"\n\n[model_providers.ccapi]\nname = "CCAPI"\nbase_url = "${i.baseURL}"\nenv_key = "OPENAI_API_KEY"\n` },
  { id:'cherry', name:'Cherry Studio', paths:platformPaths({darwin:[join('Library/Application Support/CherryStudio/config.json')],win32:[join('AppData/Roaming/CherryStudio/config.json')],linux:[join('.config/CherryStudio/config.json')]}), format:'json', patch:(c,i)=>({...c, providers:[...(c.providers||[]).filter(x=>x.name!=='CCAPI'),{name:'CCAPI',type:'openai',baseURL:i.baseURL,apiKey:i.apiKey,models:[i.model]}]}) },
  { id:'lobe', name:'LobeChat / NextChat', paths:platformPaths({darwin:[join('.lobechat/config.json'),join('.nextchat/config.json')],win32:[join('AppData/Roaming/LobeChat/config.json'),join('AppData/Roaming/NextChat/config.json')],linux:[join('.config/lobechat/config.json'),join('.config/nextchat/config.json')]}), format:'json', patch:(c,i)=>({...c, OPENAI_API_KEY:i.apiKey, OPENAI_PROXY_URL:i.baseURL, CUSTOM_MODELS:i.model}) },
  { id:'openclaw', name:'OpenClaw', paths:platformPaths({darwin:[join('.openclaw/config.json'),join('.config/openclaw/config.json')],win32:[join('AppData/Roaming/OpenClaw/config.json')],linux:[join('.config/openclaw/config.json')]}), format:'json', patch:(c,i)=>({...c, providers:{...(c.providers||{}),ccapi:{baseURL:i.baseURL,apiKey:i.apiKey,models:[i.model]}}}) },
  { id:'cline', name:'Cline', paths:platformPaths({darwin:[join('.cline/config.json')],win32:[join('AppData/Roaming/Cline/config.json')],linux:[join('.cline/config.json')]}), format:'json', patch:(c,i)=>({...c, apiProvider:'openai-compatible', openAiBaseUrl:i.baseURL, openAiApiKey:i.apiKey, openAiModelId:i.model}) },
  { id:'continue', name:'Continue', paths:platformPaths({darwin:[join('.continue/config.yaml')],win32:[join('.continue/config.yaml')],linux:[join('.continue/config.yaml')]}), format:'yaml', patch:(_,i)=>`name: CCAPI\nversion: 1.0.0\nmodels:\n  - name: ${i.model}\n    provider: openai\n    model: ${i.model}\n    apiBase: ${i.baseURL}\n    apiKey: ${i.apiKey}\n` },
  { id:'chatbox', name:'Chatbox', paths:platformPaths({darwin:[join('Library/Application Support/Chatbox/config.json')],win32:[join('AppData/Roaming/Chatbox/config.json')],linux:[join('.config/Chatbox/config.json')]}), format:'json', patch:(c,i)=>({...c, providers:[...(c.providers||[]).filter(x=>x.name!=='CCAPI'),{name:'CCAPI',apiHost:i.baseURL,apiKey:i.apiKey,model:i.model}]}) },
  { id:'generic', name:'通用 OpenAI 兼容工具', paths:platformPaths({darwin:[],win32:[],linux:[]}), format:'env', patch:(_,i)=>`OPENAI_BASE_URL=${i.baseURL}\nOPENAI_API_KEY=${i.apiKey}\nOPENAI_MODEL=${i.model}\n` }
];
function pathsFor(adapter, platform=process.platform) { return adapter.paths[platform] || []; }
module.exports = { adapters, pathsFor };
