const {app,BrowserWindow,ipcMain,safeStorage,shell,dialog}=require('electron');
const path=require('node:path');const fs=require('node:fs/promises');const fsSync=require('node:fs');
const {adapters,pathsFor}=require('./adapters');
const API_BASE='https://api-direct.ccapi.us/v1';const CONFIG_ROOT=path.join(app.getPath('userData'),'profiles');
function createWindow(){const w=new BrowserWindow({width:1180,height:820,minWidth:980,minHeight:680,title:'CCAPI Setup',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});w.loadFile(path.join(__dirname,'index.html'));}
async function safeFetch(url,o={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),20000);try{return await fetch(url,{...o,signal:c.signal})}finally{clearTimeout(t)}}
async function response(r){const text=await r.text();let data={};try{data=JSON.parse(text)}catch{}return {ok:r.ok,status:r.status,data,message:r.ok?'连接成功':data?.error?.message||`请求失败（HTTP ${r.status}）`}}
function headers(token){return {Authorization:`Bearer ${token}`,'Content-Type':'application/json'}}
ipcMain.handle('api-test',async(_,x={})=>{if(!x.token)return{ok:false,message:'请输入 API Key'};try{let r;if(x.kind==='models')r=await safeFetch(`${API_BASE}/models`,{headers:headers(x.token)});else if(x.kind==='chat')r=await safeFetch(`${API_BASE}/chat/completions`,{method:'POST',headers:headers(x.token),body:JSON.stringify({model:x.model,messages:[{role:'user',content:x.prompt||'请回复：配置成功'}],max_tokens:20})});else if(x.kind==='image')r=await safeFetch(`${API_BASE}/images/generations`,{method:'POST',headers:headers(x.token),body:JSON.stringify({model:x.model,prompt:x.prompt||'一朵白色雏菊，简洁插画',size:'1024x1024'})});else r=await safeFetch(`${API_BASE}/videos`,{method:'POST',headers:headers(x.token),body:JSON.stringify({model:x.model,prompt:x.prompt||'静态镜头，清晨光线中的白色纸船',duration:4,resolution:x.model?.includes('MiniMax')?'768p':'480p',aspect_ratio:'16:9'})});return response(r)}catch(e){return{ok:false,message:e.name==='AbortError'?'请求超时，请检查网络':'连接失败，请检查网络或 API 地址'}}});
ipcMain.handle('fetch-models',async(_,token)=>{try{const r=await safeFetch(`${API_BASE}/models`,{headers:headers(token)});const out=await response(r);if(!out.ok)return out;const list=out.data?.data||out.data?.models||[];return{ok:true,models:list}}catch(e){return{ok:false,message:'模型目录获取失败'}}});
ipcMain.handle('save-token',async(_,token)=>{if(!safeStorage.isEncryptionAvailable())return{ok:false,message:'系统密钥存储不可用'};await fs.mkdir(CONFIG_ROOT,{recursive:true});await fs.writeFile(path.join(CONFIG_ROOT,'api-key.bin'),safeStorage.encryptString(token),{mode:0o600});return{ok:true}});
ipcMain.handle('get-token',async()=>{try{return safeStorage.decryptString(await fs.readFile(path.join(CONFIG_ROOT,'api-key.bin')))}catch{return''}});
ipcMain.handle('scan-tools',async()=>adapters.map(a=>({id:a.id,name:a.name,detected:pathsFor(a).filter(fsSync.existsSync)})));
function backupName(file){return `${file}.ccapi-backup-${new Date().toISOString().replace(/[:.]/g,'-')}`}
function redact(value){return value?`${value.slice(0,3)}${'•'.repeat(Math.max(4,value.length-7))}${value.slice(-4)}`:'YOUR_API_KEY'}
async function targetFor(a){return pathsFor(a).find(fsSync.existsSync)||null}
async function buildConfig(a,file,i){let current={};if(file&&a.format==='json')current=JSON.parse(await fs.readFile(file,'utf8'));return a.patch(current,i)}
ipcMain.handle('preview-config',async(_,x)=>{const a=adapters.find(z=>z.id===x.tool);if(!a)return{ok:false,message:'未找到适配器'};const file=await targetFor(a);try{const next=await buildConfig(a,file,{baseURL:API_BASE,apiKey:redact(x.token),model:x.model});return{ok:true,file,exists:!!file,format:a.format,preview:typeof next==='string'?next:JSON.stringify(next,null,2)}}catch(e){return{ok:false,message:`配置预览失败：${e.message}`}}});
ipcMain.handle('apply-config',async(_,x)=>{const a=adapters.find(z=>z.id===x.tool);if(!a)return{ok:false,message:'未找到适配器'};const file=await targetFor(a);if(!file)return{ok:false,message:'未检测到配置文件，请使用导出配置'};try{const raw=await fs.readFile(file,'utf8');const current=a.format==='json'?JSON.parse(raw):{};const next=a.patch(current,{baseURL:API_BASE,apiKey:x.token,model:x.model});const backup=backupName(file);await fs.copyFile(file,backup);const tmp=`${file}.ccapi-tmp-${process.pid}`;await fs.writeFile(tmp,typeof next==='string'?next:JSON.stringify(next,null,2)+'\n',{mode:0o600});await fs.rename(tmp,file);if(a.format==='json')JSON.parse(await fs.readFile(file,'utf8'));return{ok:true,file,backup}}catch(e){return{ok:false,message:`配置未写入：${e.message}`}}});
ipcMain.handle('rollback-config',async(_,file)=>{const backups=(await fs.readdir(path.dirname(file))).filter(x=>x.startsWith(path.basename(file)+'.ccapi-backup-')).sort().reverse();if(!backups.length)return{ok:false,message:'没有找到备份'};await fs.copyFile(path.join(path.dirname(file),backups[0]),file);return{ok:true,file,backup:backups[0]}});
ipcMain.handle('export-config',async(_,x)=>{const a=adapters.find(z=>z.id===x.tool)||adapters.at(-1);const out=path.join(app.getPath('downloads'),`ccapi-${x.tool||'config'}.${a.format==='env'?'env':a.format}`);const content=a.patch({}, {baseURL:API_BASE,apiKey:x.includeKey?x.token:'YOUR_API_KEY',model:x.model||'gpt-6-sol'});await fs.writeFile(out,typeof content==='string'?content:JSON.stringify(content,null,2)+'\n',{mode:0o600});return out});
ipcMain.handle('open-url',(_,u)=>shell.openExternal(u));app.whenReady().then(()=>{createWindow();app.on('activate',()=>{if(!BrowserWindow.getAllWindows().length)createWindow()})});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
